config/routes.rb
Rails.application.routes.draw do
  resources :equipe_escolars
  resources :professors
  resources :responsavels
  resources :alunos
  resources :disciplinas
  resources :turmas
  resources :unidades
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/unidade.rb
class Unidade < ApplicationRecord
end

app/controllers/unidades_controller.rb
class UnidadesController < ApplicationController
  before_action :set_unidade, only: %i[ show edit update destroy ]

  # GET /unidades or /unidades.json
  def index
    @unidades = Unidade.all
  end

  # GET /unidades/1 or /unidades/1.json
  def show
  end

  # GET /unidades/new
  def new
    @unidade = Unidade.new
  end

  # GET /unidades/1/edit
  def edit
  end

  # POST /unidades or /unidades.json
  def create
    @unidade = Unidade.new(unidade_params)

    respond_to do |format|
      if @unidade.save
        ::SendSqsMessageService.new('create', 'Headquarter', @unidade, unidade_params.to_h).call

        format.html { redirect_to unidade_url(@unidade), notice: 'Unidade was successfully created.' }
        format.json { render :show, status: :created, location: @unidade }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @unidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /unidades/1 or /unidades/1.json
  def update
    respond_to do |format|
      if @unidade.update(unidade_params)
        ::SendSqsMessageService.new('update', 'Headquarter', @unidade, unidade_params.to_h).call

        format.html { redirect_to unidade_url(@unidade), notice: "Unidade was successfully updated." }
        format.json { render :show, status: :ok, location: @unidade }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @unidade.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /unidades/1 or /unidades/1.json
  def destroy
    respond_to do |format|
      if @unidade.destroy
        ::SendSqsMessageService.new('delete', 'Headquarter', @unidade, {}).call

        format.html { redirect_to unidades_url, notice: 'Unidade was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.json { render json: @unidade.errors, status: :unprocessable_entity }
      end
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_unidade
    @unidade = Unidade.find(params[:id])
  end

  # Only allow a list of trusted parameters through.
  def unidade_params
    params.require(:unidade).permit(:nome, :endereco, :telefone)
  end
end

app/helpers/unidades_helper.rb
module UnidadesHelper
end

app/views/unidades/_form.html.erb
<%= form_with(model: unidade, local: true) do |form| %>
  <% if unidade.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(unidade.errors.count, "error") %> prohibited this unidade from being saved:</h2>

      <ul>
        <% unidade.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :endereco %>
    <%= form.text_field :endereco %>
  </div>

  <div class="field">
    <%= form.label :telefone %>
    <%= form.text_field :telefone %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/unidades/edit.html.erb
<h1>Editing Unidade</h1>

<%= render 'form', unidade: @unidade %>

<%= link_to 'Show', @unidade %> |
<%= link_to 'Back', unidades_path %>

app/views/unidades/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Unidades</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Endereco</th>
      <th>Telefone</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @unidades.each do |unidade| %>
      <tr>
        <td><%= unidade.nome %></td>
        <td><%= unidade.endereco %></td>
        <td><%= unidade.telefone %></td>
        <td><%= link_to 'Show', unidade %></td>
        <td><%= link_to 'Edit', edit_unidade_path(unidade) %></td>
        <td><%= link_to 'Destroy', unidade, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Unidade', new_unidade_path %>

app/views/unidades/new.html.erb
<h1>New Unidade</h1>

<%= render 'form', unidade: @unidade %>

<%= link_to 'Back', unidades_path %>

app/views/unidades/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @unidade.nome %>
</p>

<p>
  <strong>Endereco:</strong>
  <%= @unidade.endereco %>
</p>

<p>
  <strong>Telefone:</strong>
  <%= @unidade.telefone %>
</p>

<%= link_to 'Edit', edit_unidade_path(@unidade) %> |
<%= link_to 'Back', unidades_path %>