config/routes.rb
Rails.application.routes.draw do
  resources :equipe_escolars
  resources :professors
  resources :responsavels
  resources :alunos
  resources :disciplinas
  resources :turmas
  resources :unidades
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/equipe_escolar.rb
class EquipeEscolar < ApplicationRecord
  belongs_to :turma
end

app/controllers/equipe_escolars_controller.rb
class EquipeEscolarsController < ApplicationController
  before_action :set_equipe_escolar, only: %i[ show edit update destroy ]

  # GET /equipe_escolars or /equipe_escolars.json
  def index
    @equipe_escolars = EquipeEscolar.all
  end

  # GET /equipe_escolars/1 or /equipe_escolars/1.json
  def show
  end

  # GET /equipe_escolars/new
  def new
    @equipe_escolar = EquipeEscolar.new
  end

  # GET /equipe_escolars/1/edit
  def edit
  end

  # POST /equipe_escolars or /equipe_escolars.json
  def create
    @equipe_escolar = EquipeEscolar.new(equipe_escolar_params)

    respond_to do |format|
      if @equipe_escolar.save
        ::SendSqsMessageService.new('create', 'Team', @equipe_escolar, equipe_escolar_params.to_h).call

        format.html { redirect_to equipe_escolar_url(@equipe_escolar), notice: "Equipe escolar was successfully created." }
        format.json { render :show, status: :created, location: @equipe_escolar }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @equipe_escolar.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /equipe_escolars/1 or /equipe_escolars/1.json
  def update
    respond_to do |format|
      if @equipe_escolar.update(equipe_escolar_params)
        ::SendSqsMessageService.new('update', 'Team', @equipe_escolar, equipe_escolar_params.to_h).call

        format.html { redirect_to equipe_escolar_url(@equipe_escolar), notice: "Equipe escolar was successfully updated." }
        format.json { render :show, status: :ok, location: @equipe_escolar }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @equipe_escolar.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /equipe_escolars/1 or /equipe_escolars/1.json
  def destroy
    respond_to do |format|
      if @equipe_escolar.destroy
        ::SendSqsMessageService.new('delete', 'Team', @equipe_escolar, {}).call

        format.html { redirect_to equipe_escolars_url, notice: 'equipe_escolar was successfully destroyed.' }
        format.json { head :no_content }
      else
        format.json { render json: @equipe_escolar.errors, status: :unprocessable_entity }
      end
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_equipe_escolar
      @equipe_escolar = EquipeEscolar.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def equipe_escolar_params
      params.require(:equipe_escolar).permit(:nome, :cargo, :turma_id)
    end
end

app/helpers/equipe_escolars_helper.rb
module EquipeEscolarsHelper
end

app/views/equipe_escolars/_form.html.erb
<%= form_with(model: equipe_escolar, local: true) do |form| %>
  <% if equipe_escolar.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(equipe_escolar.errors.count, "error") %> prohibited this equipe_escolar from being saved:</h2>

      <ul>
        <% equipe_escolar.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :nome %>
    <%= form.text_field :nome %>
  </div>

  <div class="field">
    <%= form.label :cargo %>
    <%= form.text_field :cargo %>
  </div>

  <div class="field">
    <%= form.label :turma_id %>
    <%= form.text_field :turma_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/equipe_escolars/edit.html.erb
<h1>Editing Equipe Escolar</h1>

<%= render 'form', equipe_escolar: @equipe_escolar %>

<%= link_to 'Show', @equipe_escolar %> |
<%= link_to 'Back', equipe_escolars_path %>

app/views/equipe_escolars/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Equipe Escolars</h1>

<table>
  <thead>
    <tr>
      <th>Nome</th>
      <th>Cargo</th>
      <th>Turma</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @equipe_escolars.each do |equipe_escolar| %>
      <tr>
        <td><%= equipe_escolar.nome %></td>
        <td><%= equipe_escolar.cargo %></td>
        <td><%= equipe_escolar.turma_id %></td>
        <td><%= link_to 'Show', equipe_escolar %></td>
        <td><%= link_to 'Edit', edit_equipe_escolar_path(equipe_escolar) %></td>
        <td><%= link_to 'Destroy', equipe_escolar, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Equipe Escolar', new_equipe_escolar_path %>

app/views/equipe_escolars/new.html.erb
<h1>New Equipe Escolar</h1>

<%= render 'form', equipe_escolar: @equipe_escolar %>

<%= link_to 'Back', equipe_escolars_path %>

app/views/equipe_escolars/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Nome:</strong>
  <%= @equipe_escolar.nome %>
</p>

<p>
  <strong>Cargo:</strong>
  <%= @equipe_escolar.cargo %>
</p>

<p>
  <strong>Turma:</strong>
  <%= @equipe_escolar.turma_id %>
</p>

<%= link_to 'Edit', edit_equipe_escolar_path(@equipe_escolar) %> |
<%= link_to 'Back', equipe_escolars_path %>